# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.6
  - 3.5
  - 3.4

install:
  - sudo apt-get -y install pandoc
  - pip install -r requirements_dev.txt
  - python setup.py install

script:
  - py.test


